# Generated by Django 3.0 on 2020-11-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_detach'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sidebar',
            field=models.BooleanField(default=False),
        ),
    ]
