# Generated by Django 3.0 on 2020-11-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='footer',
            field=models.BooleanField(default=False),
        ),
    ]
