# Generated by Django 3.0 on 2020-11-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='image',
            new_name='file',
        ),
    ]
